apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: monitoring
data:
  additional-scrape-configs.yaml: |
    - job_name: 'k8s-api-cert'
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
            - https://kubernetes.default.svc.cluster.local/readyz
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 163.43.128.7:9115
