global:
  rbac:
    pspEnable: false

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30000
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "k8s-api-cert"
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              - https://kubernetes.default.svc.cluster.local/readyz
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 163.43.128.7:9115

    additionalScrapeConfigsSecret: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        app: prometheus-blackbox-exporter
  service:
    type: NodePort
    nodePort: 31000

alertmanager:
  enabled: true
