global:
  rbac:
    pspEnable: false

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30000
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      name: additional-scrape-configs
      key: additional-scrape-configs.yaml
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        app: prometheus-blackbox-exporter
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    ruleSelector: {}
  service:
    type: NodePort
    nodePort: 31000

alertmanager:
  enabled: true
