global:
  rbac:
    pspEnable: false

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30000
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        app: prometheus-blackbox-exporter
  service:
    type: NodePort
    nodePort: 31000

alertmanager:
  enabled: true
