global:
  rbac:
    pspEnable: false

grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30000
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        app: prometheus-blackbox-exporter

    ruleSelector:
      matchLabels:
        prometheus: kube-prometheus-stack

    additionalScrapeConfigs:
      - job_name: "k8s-api-cert"
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              - https://kubernetes.default.svc.cluster.local/readyz
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 163.43.128.7:9115

    additionalPrometheusRulesMap:
      ssl-cert-expiry-alerts:
        groups:
          - name: SSLExpiryAlerts
            rules:
              - alert: SSLCertificateExpiry
                expr: (probe_ssl_earliest_cert_expiry - time()) / 86400 < 365
                for: 10s
                labels:
                  severity: warning
                annotations:
                  summary: "SSL certificate is expiring within a year."
                  description: "The SSL certificate for {{ $labels.instance }} is expiring in less than 365 days."

  service:
    type: NodePort
    nodePort: 31000

alertmanager:
  enabled: true
