service:
  type: NodePort
  port: 9115
  nodePort: 31559
  name: http

image:
  registry: quay.io
  repository: prometheus/blackbox-exporter
  tag: "v0.27.0"
  pullPolicy: IfNotPresent

config:
  modules:
    # TLS証明書チェック用モジュール
    ssl_cert:
      prober: tls
      timeout: 10s
