service:
  type: NodePort
  port: 9115
  nodePort: 31559
  name: http

config:
  modules:
    http_2xx:
      http:
        follow_redirects: true
        tls_config:
          insecure_skip_verify: true
