service:
  type: NodePort
  port: 9115
  nodePort: 31559
  name: http

image:
  registry: quay.io
  repository: prometheus/blackbox-exporter
  tag: "v0.27.0"
  pullPolicy: IfNotPresent

config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        preferred_ip_protocol: ip4
        ip_protocol_fallback: true
        follow_redirects: true
        enable_http2: true
        tls_config:
          insecure_skip_verify: true
      tcp:
        ip_protocol_fallback: true
      icmp:
        ip_protocol_fallback: true
        ttl: 64
      dns:
        ip_protocol_fallback: true
        recursion_desired: true
        