apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-apps
  namespace: argocd
spec:
  project: "dev"
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: git@github.com:ippanpeople/black_box.git
    path: "argocd/dev-apps/"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
