apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: black-box-exporter
  namespace: argocd
spec:
  project: "dev"
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: git@github.com:ippanpeople/black_box.git
    path: "helm/dev-charts/black-box-exporter"
    plugin:
      name: argocd-vault-plugin-kustomize-helmcharts
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
