apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-blackbox-exporter
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-blackbox-exporter
      targetRevision: 9.2.0
      helm:
        releaseName: prometheus-blackbox-exporter
        skipCrds: true
        valueFiles:
          - $values/helm/dev-charts/prometheus-blackbox-exporter/values.yaml
    - repoURL: 'git@github.com:ippanpeople/black_box.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
