apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
    sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 62.3.1
      helm:
        releaseName: kube-prometheus-stack
        skipCrds: true  # Skip CRD installation as it's handled by the other app
        valueFiles:
          - $values/helm/dev-charts/kube-prometheus-stack/values.yaml
    - repoURL: 'https://github.sakura.codes/w-rin/shared-k8s-dev.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
