apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 62.3.1
      helm:
        releaseName: kube-prometheus-stack
        skipCrds: true
    - repoURL: 'git@github.com:ippanpeople/black_box.git'
      targetRevision: HEAD
      path: helm/dev-charts/kube-prometheus-stack
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
